# helm upgrade --install nginx-test -f values.yaml .
apiVersion: v1
description: Ong Helm Chart
name: ong-helm
version: 1.0.0
appVersion: 1.0.0
maintainers:
  - name: Peerawit
    email: peerawit.k@appman.co.th