apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.ong-test.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: ong-test
      app.kubernetes.io/name: {{ .Release.Name }}
  replicas: {{ .Values.ong-test.replicas }}
  template:
    metadata:
      labels:
        app: ong-test
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      containers:
      - name: ong-test
        image: {{ .Values.ong-test.image }}
        ports:
        - containerPort: 80