apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.ong-test.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  ingressClassName: {{ .Values.ong-test.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.ong-test.host }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 80